name: Execute SQL Script

resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true
    - repository: pipelineProject
      type: github
      endpoint: sam-hiscox
      name: sam-hiscox/Script-Execution-Pipeline-Project
    - repository: database-scripts
      type: git
      ref: main
      name: database-scripts

trigger:
  - '*'

variables:
  - group: platform-global

####### DEV #######
stages:
  - template: Templates/infrastructure-stage.yml
    parameters:
      stageName: DeployInfrastructureDev
      environmentName: dev
      EnvironmentId: d01
      serviceConnection: $(devServiceConnection)
      location: 'uksouth'
      resourceGroupName: 'sql-automation-dev'
      subscriptionId: $(subscriptionID)
      applicationName: sql-automation

  - template: Templates/test-sql-script-stage.yml
    parameters:
      environmentName: dev
      variableGroups: 
        - platform-dev-sql-automation

  - template: Templates/execute-sql-script-stage.yml
    parameters:
      variableGroups: 
        - platform-dev-sql-automation
      environmentName: dev
      serviceConnection: $(devServiceConnection)
      resourceEnvironmentName: d01

####### TEST #######

  - template: Templates/infrastructure-stage.yml
    parameters:
      stageName: DeployInfrastructureTest
      environmentName: tst
      EnvironmentId: t01
      serviceConnection: $(devServiceConnection)
      location: 'uksouth'
      resourceGroupName: 'sql-automation-tst'
      subscriptionId: $(subscriptionID)
      applicationName: sql-automation

  - template: Templates/test-sql-script-stage.yml
    parameters:
      environmentName: tst  
      variableGroups: 
        - platform-tst-sql-automation

  - template: templates/execute-sql-script-stage.yml
    parameters:
      variableGroups: 
        - platform-tst-sql-automation
      environmentName: tst
      serviceConnection: $(devServiceConnection)
      resourceEnvironmentName: t01

####### PRE-PROD #######

  - template: Templates/infrastructure-stage.yml
    parameters:
      stageName: DeployInfrastructurePreProd
      environmentName: ppd
      EnvironmentId: p02
      serviceConnection: $(devServiceConnection)
      location: 'uksouth'
      resourceGroupName: 'sql-automation-ppd'
      subscriptionId: $(subscriptionID)
      applicationName: sql-automation

  - template: Templates/test-sql-script-stage.yml
    parameters:
      environmentName: ppd
      variableGroups: 
        - platform-ppd-sql-automation

  - template: templates/execute-sql-script-stage.yml
    parameters:
      variableGroups: 
        - platform-tst-sql-automation
      environmentName: ppd
      serviceConnection: $(devServiceConnection)
      resourceEnvironmentName: p02