stages:
  - template: tlevels-build-stage.yml
    parameters:        
      variableGroups:
        - platform-global
######################## DEV ##############################################
  - template: pipeline-infrastructure-stage.yml
    parameters:
      environmentTagName: Dev
      stageName: Dev
      environmentName: dev
      EnvironmentId: d01
      serviceConnection: $(devServiceConnection)
      applicationName: sql-automation-platform
      location: 'West Europe'

######################## TEST ##############################################
  - template: pipeline-infrastructure-stage.yml
    parameters:
      environmentTagName: Test
      stageName: Test
      dependencies:
        - dev
      environmentName: tst
      EnvironmentId: t01
      serviceConnection: $(devServiceConnection)
      applicationName: sql-automation-platform
      location: 'West Europe'
